const SUBJECT_GUIDE_PREFIX = 'cambridge-'

/** Slugs generated by scripts/generate-subject-blog-posts.mjs */
export function isSubjectGuideSlug(slug: string): boolean {
  return slug.startsWith(SUBJECT_GUIDE_PREFIX) && slug.endsWith('-past-papers-guide')
}
