import { getBlogPosts, type BlogPostMeta } from '@/lib/blog'

const SUBJECT_GUIDE_PREFIX = 'cambridge-'

/** Slugs generated by scripts/generate-subject-blog-posts.mjs */
export function isSubjectGuideSlug(slug: string): boolean {
  return (
    slug.startsWith(SUBJECT_GUIDE_PREFIX) &&
    slug.endsWith('-past-papers-guide')
  )
}

export function getSubjectGuideSlugForCode(code: string): string | null {
  const prefix = `${SUBJECT_GUIDE_PREFIX}${code}-`
  const post = getBlogPosts().find((p) => p.slug.startsWith(prefix))
  return post?.slug ?? null
}

export function getSubjectGuidePosts(): BlogPostMeta[] {
  return getBlogPosts().filter((p) => isSubjectGuideSlug(p.slug))
}

export function getNonSubjectGuidePosts(): BlogPostMeta[] {
  return getBlogPosts().filter((p) => !isSubjectGuideSlug(p.slug))
}
