import type { LineReference } from '@/components/examiner-ink/ExaminerInkOverlay'

/**
 * Examiner ink for the demo script — the product's signature moment.
 *
 * A score ring shows a number; this shows the thing nobody expects software to
 * do: red pen on your own handwriting, stamped against the line that earned or
 * lost the mark. That is the image a student remembers, and it was only ever
 * visible after a real 100-second mark — never to anyone deciding whether to
 * try it.
 *
 * Boxes are exact, not eyeballed: the script image is generated by
 * scripts/generate-demo-script-image.mjs and these percentages are computed
 * from the same layout constants it prints. Change one, re-run it, update both.
 *
 * The five marks match DEMO_MARK_RESULT exactly, so the ink, the score ring and
 * the mark list on every surface describe one script.
 */

export const DEMO_SCRIPT_IMAGE = '/demo/handwritten-script.webp'

const LEFT = 12.0
const HEIGHT = 3.94

export const DEMO_INK: LineReference[] = [
  {
    mark_id: 'M1',
    earned: true,
    margin_note: null,
    error_classification: 'no_error',
    bbox: { top: 7.90, left: LEFT, width: 31.28, height: HEIGHT },
    snippet: 'dy/dx = 3x^2 - 12x + 9',
  },
  {
    mark_id: 'M1',
    earned: true,
    margin_note: null,
    error_classification: 'no_error',
    bbox: { top: 25.62, left: LEFT, width: 25.59, height: HEIGHT },
    snippet: '(x - 1)(x - 3) = 0',
  },
  {
    mark_id: 'A1',
    earned: true,
    margin_note: null,
    error_classification: 'no_error',
    bbox: { top: 31.53, left: LEFT, width: 22.75, height: HEIGHT },
    snippet: 'x = 1  or  x = 3',
  },
  {
    mark_id: 'A1',
    earned: true,
    margin_note: null,
    error_classification: 'no_error',
    bbox: { top: 49.26, left: LEFT, width: 51.19, height: HEIGHT },
    snippet: 'stationary points: (1, 5) and (3, 1)',
  },
  // The one that matters — a correct conclusion with nothing behind it.
  {
    mark_id: 'A1',
    earned: false,
    margin_note: 'Correct — but you never showed why',
    error_classification: 'incomplete_method',
    bbox: { top: 55.17, left: LEFT, width: 56.87, height: HEIGHT },
    snippet: '(1, 5) is a maximum, (3, 1) is a minimum',
  },
]
