/**
 * Paper/component structure derived from Supabase Storage (`paper-pdfs`).
 * Cache generated by: node scripts/generate-subject-papers-cache.mjs
 */

import cache from './subject-papers-cache.json'

export type SubjectPaperGroup = {
  paper: number
  name: string
  components: string[]
}

export type SubjectPaperStructure = {
  code: string
  papers: SubjectPaperGroup[]
  sessions: string[]
}

type CacheMap = Record<string, SubjectPaperStructure>

const CACHE = cache as CacheMap

export function getSubjectPaperStructure(
  code: string
): SubjectPaperStructure | null {
  return CACHE[code] ?? null
}

export function getAllCachedSubjectCodes(): string[] {
  return Object.keys(CACHE).sort()
}

export function hasPaperPdfsInStorage(code: string): boolean {
  return code in CACHE
}
