// AUTO-GENERATED by scripts/gen-syllabus-index.mjs — do not edit by hand.
// Run `node scripts/gen-syllabus-index.mjs` after changing the outcome files.
import o9084 from './9084.json'
import o9700 from './9700.json'
import o9702 from './9702.json'
import o9706 from './9706.json'

export type Outcome = { code: string; topic: string; text: string }

export const SYLLABUS_OUTCOMES: Record<string, Outcome[]> = {
  '9084': o9084 as Outcome[],
  '9700': o9700 as Outcome[],
  '9702': o9702 as Outcome[],
  '9706': o9706 as Outcome[],
}
