-- Sprint 24: Teacher/Tutor Analytics Dashboard — multi-tenant classroom system
-- Run this in the Supabase SQL editor before using teacher features.

-- Role enum on user profiles
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'student' CHECK (role IN ('student', 'teacher'));

-- Classrooms table
CREATE TABLE IF NOT EXISTS classrooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  invite_code TEXT UNIQUE DEFAULT substring(md5(random()::text) for 8),
  board TEXT DEFAULT 'Cambridge International',
  level TEXT DEFAULT 'A-Level',
  subject TEXT DEFAULT 'Mathematics',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_classrooms_teacher ON classrooms(teacher_id);
CREATE INDEX IF NOT EXISTS idx_classrooms_invite ON classrooms(invite_code);

-- Many-to-many: students in classrooms
CREATE TABLE IF NOT EXISTS classroom_memberships (
  classroom_id UUID NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (classroom_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_student ON classroom_memberships(student_id);

-- Teacher overrides on AI marks
CREATE TABLE IF NOT EXISTS teacher_overrides (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  attempt_id UUID NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
  teacher_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  original_marks_awarded JSONB NOT NULL,
  override_marks_awarded JSONB NOT NULL,
  override_total_earned NUMERIC NOT NULL,
  teacher_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_overrides_attempt ON teacher_overrides(attempt_id);
CREATE INDEX IF NOT EXISTS idx_overrides_teacher ON teacher_overrides(teacher_id);

-- Intervention tests generated by teachers
CREATE TABLE IF NOT EXISTS intervention_tests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  classroom_id UUID NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
  teacher_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  target_syllabus_codes TEXT[] NOT NULL,
  question_ids UUID[] NOT NULL,
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: classrooms only visible to their teacher
ALTER TABLE classrooms ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS classroom_teacher_access ON classrooms;
CREATE POLICY classroom_teacher_access ON classrooms
  FOR ALL USING (auth.uid() = teacher_id);

DROP POLICY IF EXISTS classroom_student_read ON classrooms;
CREATE POLICY classroom_student_read ON classrooms
  FOR SELECT USING (
    id IN (SELECT classroom_id FROM classroom_memberships WHERE student_id = auth.uid())
  );

-- Memberships RLS
ALTER TABLE classroom_memberships ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS membership_teacher_manage ON classroom_memberships;
CREATE POLICY membership_teacher_manage ON classroom_memberships
  FOR ALL USING (
    classroom_id IN (SELECT id FROM classrooms WHERE teacher_id = auth.uid())
  );

DROP POLICY IF EXISTS membership_student_read ON classroom_memberships;
CREATE POLICY membership_student_read ON classroom_memberships
  FOR SELECT USING (student_id = auth.uid());

-- Teachers can read attempts of their students (cross-tenant query)
DROP POLICY IF EXISTS teacher_read_student_attempts ON attempts;
CREATE POLICY teacher_read_student_attempts ON attempts
  FOR SELECT USING (
    user_id IN (
      SELECT cm.student_id
      FROM classroom_memberships cm
      JOIN classrooms c ON cm.classroom_id = c.id
      WHERE c.teacher_id = auth.uid()
    )
  );

-- Overrides RLS
ALTER TABLE teacher_overrides ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS override_teacher_access ON teacher_overrides;
CREATE POLICY override_teacher_access ON teacher_overrides
  FOR ALL USING (auth.uid() = teacher_id);

DROP POLICY IF EXISTS override_student_read ON teacher_overrides;
CREATE POLICY override_student_read ON teacher_overrides
  FOR SELECT USING (
    attempt_id IN (SELECT id FROM attempts WHERE user_id = auth.uid())
  );

-- Intervention tests RLS
ALTER TABLE intervention_tests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS intervention_teacher_access ON intervention_tests;
CREATE POLICY intervention_teacher_access ON intervention_tests
  FOR ALL USING (auth.uid() = teacher_id);

DROP POLICY IF EXISTS intervention_student_read ON intervention_tests;
CREATE POLICY intervention_student_read ON intervention_tests
  FOR SELECT USING (
    classroom_id IN (SELECT classroom_id FROM classroom_memberships WHERE student_id = auth.uid())
  );
