import { GEMINI_PRO_MODEL, generateGeminiText } from '@/lib/ai/gemini-text'
import { extractJSON } from '@/lib/marking/json'
import { supabaseAdmin } from '@/lib/marking/mark-runner'
import { getSyllabusTopicByCode } from '@/lib/syllabi'
import { getIbMarkingProfile, type IbMarkingProfile } from '@/lib/ib/marking-config'

/**
 * A real IB practice question for one syllabus topic — replaces the old "submit
 * your work" stub so the drill loop hands IB students something concrete to
 * answer (parity with the Cambridge past-paper drill). Generated by the marking
 * model and cached per (subject, topic) in `ib_practice_questions`.
 */
export type IbPracticeQuestion = {
  question_text: string
  total_marks: number | null
  component: string | null
}

/** Authoritative mark total: criteria sum for essay/criteria subjects, else the
 * profile's practice max. Never trusted from the model. */
function targetMarks(profile: IbMarkingProfile): number {
  if (profile.criteria?.length) {
    return profile.criteria.reduce((sum, c) => sum + c.maxMarks, 0)
  }
  return profile.practiceMaxMarks
}

function buildPrompt(
  profile: IbMarkingProfile,
  topicName: string,
  component: string | null,
  marks: number
): string {
  const isCriteria =
    !!profile.criteria?.length || profile.practiceStyle === 'level_of_response'
  const criteriaLine = profile.criteria?.length
    ? `It will be marked against these criteria: ${profile.criteria
        .map((c) => `${c.id} ${c.name} (/${c.maxMarks})`)
        .join('; ')}.`
    : profile.markingBlurb

  return [
    `You are a senior IB examiner writing ONE authentic exam-style practice question for ${profile.name} (${profile.level}, ${profile.group})${component ? `, ${component}` : ''}.`,
    '',
    `TOPIC: ${topicName}`,
    `TARGET MARKS: ${marks}`,
    criteriaLine,
    '',
    'INSTRUCTIONS:',
    `- Write a single question that genuinely tests "${topicName}" at IB ${profile.level} standard, in the exact style and command terms IB uses for this component.`,
    isCriteria
      ? '- This is an extended-response/essay component: produce a focused essay title or prompt a student can respond to in prose. Do not include mark-by-mark breakdowns.'
      : `- This is a structured/points component: produce a self-contained question worth exactly ${marks} marks. State the mark allocation in brackets, e.g. "[${marks}]", and use IB command terms (State, Outline, Explain, Deduce, Discuss, etc.).`,
    '- Do NOT provide the answer, mark scheme, or examiner notes — only the question a student would see.',
    '- Keep it realistic and self-contained (no reference to figures/data the student cannot see).',
    '',
    'Return ONLY valid JSON, no prose:',
    '{ "question_text": "the question exactly as a student would see it (use \\n for line breaks, $...$ for maths)" }',
  ]
    .filter(Boolean)
    .join('\n')
}

/** Generate (no cache). Best-effort — returns null on any model/parse failure. */
export async function generateIbPracticeQuestion(
  subjectCode: string,
  topicCode: string
): Promise<IbPracticeQuestion | null> {
  const profile = getIbMarkingProfile(subjectCode)
  if (!profile) return null

  const topic = getSyllabusTopicByCode(subjectCode, topicCode)
  const topicName = topic?.name ?? topicCode
  const component = topic?.paper ?? null
  const marks = targetMarks(profile)

  try {
    const text = await generateGeminiText(
      buildPrompt(profile, topicName, component, marks),
      {
        task: 'structured-extraction',
        model: GEMINI_PRO_MODEL,
        maxOutputTokens: 900,
        temperature: 0.5,
      }
    )
    const parsed = extractJSON(text) as { question_text?: string }
    const question = parsed?.question_text?.trim()
    if (!question || question.length < 12) return null
    return { question_text: question, total_marks: marks, component }
  } catch (err) {
    console.warn('[ib-practice] question generation failed', err)
    return null
  }
}

/**
 * Cached generation: return the stored question for this topic, else generate one
 * and cache it. All cache access is best-effort — a missing `ib_practice_questions`
 * table (migration not yet applied) or any DB error just falls through to a fresh
 * generation, so caching is a pure optimisation, never a correctness dependency.
 */
export async function getOrCreateIbPracticeQuestion(
  subjectCode: string,
  topicCode: string
): Promise<IbPracticeQuestion | null> {
  try {
    const { data } = await supabaseAdmin
      .from('ib_practice_questions')
      .select('question_text, total_marks, component')
      .eq('subject_code', subjectCode)
      .eq('topic_code', topicCode)
      .maybeSingle()
    if (data?.question_text) {
      return {
        question_text: data.question_text as string,
        total_marks: (data.total_marks as number | null) ?? null,
        component: (data.component as string | null) ?? null,
      }
    }
  } catch {
    // Cache unavailable (table missing / transient) — regenerate below.
  }

  const generated = await generateIbPracticeQuestion(subjectCode, topicCode)
  if (!generated) return null

  try {
    await supabaseAdmin.from('ib_practice_questions').upsert(
      {
        subject_code: subjectCode,
        topic_code: topicCode,
        question_text: generated.question_text,
        total_marks: generated.total_marks,
        component: generated.component,
      },
      { onConflict: 'subject_code,topic_code' }
    )
  } catch {
    // Non-fatal — the caller still gets the generated question.
  }

  return generated
}
